import React from "react";
import { Hero, Main } from "@/components";
import Head from "next/head";
import { GetStaticProps } from "next/types";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function Home() {
  return (
    <div className="flex flex-col justify-between h-full">
      <Head>
        <title>Enzo Retamozo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <section>
        <Hero />
      </section>
    </div>
  );
}

type StaticProps = {
  locale: string;
};

export async function getStaticProps({ locale }: StaticProps) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["main", "footer", "navbar"])),
      // Will be passed to the page component as props
    },
  };
}
